/*
* @description	This class contains all unit tests for {{ trigger_name }}TriggerHandler.cls.
* @author		{{ author }}
* @deprecated	False
*/
@IsTest
private class {{ trigger_name }}TriggerHandlerTest {

	/*
	* @description
	* @author		{{ author }}
	* @return
	* @param
	* @throws
	* @deprecated	False
	* @profile
	*/
	@IsTest
	private static void unitTest1_runAs () {}

	/*
	* @description	This method inserts the initial test data. It inserts the following objects & volumes:
	*				Object:			X records
	* @author		{{ author }}
	* @return
	* @param
	* @throws
	* @deprecated	False
	*/
	@TestSetup
	private static void setupTestData () {}
}
